# Generated by Django 4.2.4 on 2023-08-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_reservation_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='user',
        ),
    ]
